version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - path: .env
        required: false
      - .env.example
    ports:
      - '${PORT:-4000}:${PORT:-4000}'

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server
    env_file:
      - path: .env
        required: false
      - .env.example
    ports:
      - '${CLIENT_PORT:-5173}:${CLIENT_PORT:-5173}'
