version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - .env.example
    ports:
      - '4000:4000'

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server
    env_file:
      - .env.example
    ports:
      - '5173:5173'
