version: '3.9'

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env.example
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    depends_on:
      - db
    env_file:
      - .env.example
    ports:
      - '4000:4000'

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server
    env_file:
      - .env.example
    ports:
      - '5173:5173'

volumes:
  postgres_data:
