version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - '${PORT:-4000}:4000'
    env_file:
      - path: .env.example
      - path: .env
        required: false
    environment:
      ENV_FILE_USED: '${ENV_FILE_USED:-.env.example}'

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server
    env_file:
      - path: .env.example
      - path: .env
        required: false
    environment:
      ENV_FILE_USED: '${ENV_FILE_USED:-.env.example}'
    ports:
      - '${CLIENT_PORT:-5173}:5173'
